cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED SOURCE_DIR OR NOT DEFINED MANIFEST)
  message(FATAL_ERROR "SOURCE_DIR and MANIFEST are required")
endif()
file(STRINGS "${MANIFEST}" _headers)
if(NOT _headers)
  message(FATAL_ERROR "SDK contract manifest is empty")
endif()
set(_unique ${_headers})
list(REMOVE_DUPLICATES _unique)
list(LENGTH _headers _count)
list(LENGTH _unique _unique_count)
if(NOT _count EQUAL _unique_count)
  message(FATAL_ERROR "SDK contract manifest contains duplicate entries")
endif()
set(_standard_headers algorithm array chrono compare cstddef cstdint limits memory
  optional span string string_view system_error type_traits utility variant vector)
foreach(_header IN LISTS _headers)
  if(NOT _header MATCHES "^core/database/[a-z_]+\\.h$" AND
     NOT _header MATCHES "^core/util/(deadline|result)\\.h$" AND
     NOT _header STREQUAL "core/transport/i_transport.h")
    message(FATAL_ERROR "Invalid SDK contract manifest entry: ${_header}")
  endif()
  if(_header MATCHES "/(generic_database_connection|i_protocol_parser|parsed_query_result|connection_pool|session_owner|database_factory|native_type_resolution)\\.h$")
    message(FATAL_ERROR "Private implementation in SDK contract manifest: ${_header}")
  endif()
  if(NOT EXISTS "${SOURCE_DIR}/${_header}")
    message(FATAL_ERROR "Missing SDK contract header: ${_header}")
  endif()
  file(READ "${SOURCE_DIR}/${_header}" _contents)
  if(_contents MATCHES "ODBCPP_ENABLE_(POSTGRESQL|REDSHIFT|MYSQL|SQLSERVER)" OR
     _contents MATCHES "(^|[^A-Za-z0-9_])(SQL(HENV|HDBC|HSTMT|HDESC|HANDLE|CHAR|WCHAR|SMALLINT|INTEGER|RETURN)|PgProtocolParser|PgDatabaseConnection)([^A-Za-z0-9_]|$)" OR
     _contents MATCHES "(^|[^A-Za-z0-9_])(SSL_CTX|SSL|BIO|X509|EVP_[A-Za-z0-9_]+|OSSL_[A-Za-z0-9_]+|RSA|EC_KEY|BIGNUM)[ \t]*[*&]" OR
     _contents MATCHES "(struct|class)[ \t]+(SSL_CTX|SSL|BIO|X509|EVP_[A-Za-z0-9_]+|OSSL_[A-Za-z0-9_]+|RSA|EC_KEY|BIGNUM)[ \t]*[;{]")
    message(FATAL_ERROR "Backend/ODBC/crypto type or selection leaked into SDK contract: ${_header}")
  endif()
  file(STRINGS "${SOURCE_DIR}/${_header}" _includes REGEX "^[ \t]*#[ \t]*include")
  foreach(_line IN LISTS _includes)
    if(NOT _line MATCHES "^[ \t]*#[ \t]*include[ \t]*([<\"])([^>\"]+)[>\"]")
      message(FATAL_ERROR "Unverifiable SDK contract include: ${_header}: ${_line}")
    endif()
    set(_delimiter "${CMAKE_MATCH_1}")
    set(_include "${CMAKE_MATCH_2}")
    if(_delimiter STREQUAL "<")
      if(NOT _include IN_LIST _standard_headers)
        message(FATAL_ERROR "Non-standard dependency in SDK contract: ${_header}: ${_include}")
      endif()
    else()
      if(_include MATCHES "^core/")
        set(_dependency "${_include}")
      else()
        get_filename_component(_parent "${SOURCE_DIR}/${_header}" DIRECTORY)
        get_filename_component(_absolute "${_include}" ABSOLUTE BASE_DIR "${_parent}")
        file(RELATIVE_PATH _dependency "${SOURCE_DIR}" "${_absolute}")
      endif()
      if(NOT _dependency IN_LIST _headers)
        message(FATAL_ERROR "Unlisted dependency in SDK contract: ${_header}: ${_include}")
      endif()
    endif()
  endforeach()
endforeach()
