cmake_minimum_required(VERSION 3.20)
foreach(_name IN ITEMS CORE DRIVER PROTOTYPE INSPECTOR)
  if(NOT EXISTS "${${_name}}")
    message(FATAL_ERROR "Missing prototype artifact inspection input: ${_name}")
  endif()
endforeach()
foreach(_kind IN ITEMS CORE DRIVER PROTOTYPE)
  if(PLATFORM STREQUAL "Windows")
    if(_kind STREQUAL "DRIVER")
      # PE release DLLs need not retain a COFF symbol table. Full static-archive
      # inspection plus source/object quarantine protect hidden implementation;
      # this check independently verifies the shipped DLL export surface.
      set(_options /EXPORTS)
    else()
      set(_options /SYMBOLS)
    endif()
  elseif(PLATFORM MATCHES "^(Linux|Darwin)$")
    set(_options -C)
  else()
    message(FATAL_ERROR "Unsupported prototype artifact inspector platform: ${PLATFORM}")
  endif()
  execute_process(COMMAND "${INSPECTOR}" ${_options} "${${_kind}}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR _out STREQUAL "")
    message(FATAL_ERROR "Prototype artifact inspection failed for ${_kind}: ${_out}${_err}")
  endif()
  if(_kind STREQUAL "PROTOTYPE")
    # Positive control: do not accept an inspector that misses these definitions.
    if(NOT _out MATCHES "ConnectionPool" OR NOT _out MATCHES "ThreadSafeConnection")
      message(FATAL_ERROR "Inspector did not recognize the prototype archive")
    endif()
  elseif(_out MATCHES "ConnectionPool|ThreadSafeConnection|connection_pool\\.(cpp|obj)")
    message(FATAL_ERROR "Prototype pool leaked into shipped ${_kind} artifact")
  endif()
endforeach()
