if(NOT DEFINED MANIFEST OR NOT EXISTS "${MANIFEST}")
  message(FATAL_ERROR "Generated crypto manifest is missing: ${MANIFEST}")
endif()
file(READ "${MANIFEST}" _manifest)
string(JSON _schema ERROR_VARIABLE _json_error GET "${_manifest}" schemaVersion)
if(_json_error)
  message(FATAL_ERROR "Crypto manifest is invalid JSON: ${_json_error}")
endif()
string(JSON _provider GET "${_manifest}" provider)
string(JSON _linkage GET "${_manifest}" requestedLinkage)
string(JSON _version GET "${_manifest}" compileVersion)
string(JSON _fips GET "${_manifest}" fipsClaimed)
string(JSON _config_only GET "${_manifest}" configurationEvidenceOnly)
string(JSON _verified GET "${_manifest}" actualArtifactLinkageVerified)
if(NOT _schema EQUAL 1 OR NOT _provider STREQUAL EXPECTED_PROVIDER OR
   NOT _linkage STREQUAL EXPECTED_LINKAGE OR NOT _version)
  message(FATAL_ERROR "Crypto manifest identity/schema does not match the build")
endif()
if(_fips OR NOT _config_only OR _verified)
  message(FATAL_ERROR "Configure-time manifest makes an unsupported claim")
endif()
