if(NOT DEFINED EXPECTED OR NOT EXISTS "${EXPECTED}")
  message(FATAL_ERROR "Driver export allowlist is missing: ${EXPECTED}")
endif()
file(STRINGS "${EXPECTED}" _expected)
list(FILTER _expected EXCLUDE REGEX "^[ \t]*(#.*)?$")
list(TRANSFORM _expected STRIP)
list(SORT _expected)

if(DEFINED INSPECTION_OUTPUT)
  set(_output "${INSPECTION_OUTPUT}")
else()
  if(NOT DEFINED ARTIFACT OR NOT EXISTS "${ARTIFACT}")
    message(FATAL_ERROR "Driver artifact is missing: ${ARTIFACT}")
  endif()
  if(NOT DEFINED INSPECTOR OR NOT EXISTS "${INSPECTOR}")
    message(FATAL_ERROR "Driver export inspector is missing: ${INSPECTOR}")
  endif()
  if(PLATFORM STREQUAL "Windows")
    set(_command "${INSPECTOR}" /EXPORTS "${ARTIFACT}")
  elseif(PLATFORM STREQUAL "Darwin")
    set(_command "${INSPECTOR}" -gU "${ARTIFACT}")
  elseif(PLATFORM STREQUAL "Linux")
    set(_command "${INSPECTOR}" -D --defined-only "${ARTIFACT}")
  else()
    message(FATAL_ERROR "Driver export inspection is unsupported on ${PLATFORM}")
  endif()
  execute_process(
    COMMAND ${_command}
    RESULT_VARIABLE _result
    OUTPUT_VARIABLE _output
    ERROR_VARIABLE _error)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Driver export inspection failed: ${_error}${_output}")
  endif()
endif()

string(REPLACE "\r\n" "\n" _output "${_output}")
string(REPLACE "\n" ";" _lines "${_output}")
set(_actual "")
foreach(_line IN LISTS _lines)
  set(_symbol "")
  if(PLATFORM STREQUAL "Windows")
    if(_line MATCHES "^[ \t]+[0-9]+[ \t]+[0-9A-Fa-f]+[ \t]+[0-9A-Fa-f]+[ \t]+([^ \t=]+)")
      set(_symbol "${CMAKE_MATCH_1}")
      if(_line MATCHES "=")
        message(FATAL_ERROR "Forwarded or aliased driver export is not allowed: ${_line}")
      endif()
    endif()
  elseif(_line MATCHES "^[0-9A-Fa-f]+[ \t]+[A-Za-z][ \t]+(.+)$")
    set(_symbol "${CMAKE_MATCH_1}")
    string(REGEX REPLACE "@@.*$" "" _symbol "${_symbol}")
    if(PLATFORM STREQUAL "Darwin")
      string(REGEX REPLACE "^_" "" _symbol "${_symbol}")
    endif()
  endif()
  if(_symbol AND NOT _symbol STREQUAL "ODBCPP_1.0")
    list(APPEND _actual "${_symbol}")
  endif()
endforeach()
list(SORT _actual)
if(NOT _actual STREQUAL _expected)
  set(_missing "${_expected}")
  set(_unexpected "${_actual}")
  foreach(_symbol IN LISTS _actual)
    list(REMOVE_ITEM _missing "${_symbol}")
  endforeach()
  foreach(_symbol IN LISTS _expected)
    list(REMOVE_ITEM _unexpected "${_symbol}")
  endforeach()
  message(FATAL_ERROR
    "Driver exports differ from the canonical ODBC allowlist.\n"
    "Missing: ${_missing}\nUnexpected: ${_unexpected}")
endif()
