# Validate qualification evidence, not a runtime driver compatibility policy.
# Standalone -P scripts do not inherit the main project's policy version.
# Quoted field names must stay literals even when variables share those names.
cmake_policy(SET CMP0054 NEW)
function(validate_crypto_identity raw manifest result error)
  set(${result} "" PARENT_SCOPE)
  set(${error} "Provider identity or TLS default policy mismatch" PARENT_SCOPE)
  string(REPLACE "\r\n" "\n" raw "${raw}")
  if(raw MATCHES "[;\r]")
    return()
  endif()
  string(REGEX REPLACE "\n$" "" raw "${raw}")
  string(REPLACE "\n" ";" lines "${raw}")
  list(LENGTH lines count)
  if(NOT count EQUAL 7)
    set(${error} "Expected seven identity fields, received ${count}" PARENT_SCOPE)
    return()
  endif()
  foreach(key provider compileVersion requestedLinkage)
    string(JSON ${key} ERROR_VARIABLE json_error GET "${manifest}" ${key})
    if(json_error)
      set(${error} "Manifest identity field ${key} is invalid: ${json_error}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  if(NOT provider STREQUAL "OPENSSL" OR
     NOT requestedLinkage MATCHES "^(SYSTEM_SHARED|BUNDLED_SHARED|BUNDLED_STATIC)$")
    return()
  endif()
  list(GET lines 0 reported_provider)
  list(GET lines 1 compiled)
  list(GET lines 2 runtime)
  list(GET lines 3 fips)
  list(GET lines 4 minimum)
  list(GET lines 5 peer)
  list(GET lines 6 hostname)
  foreach(version compiled runtime)
    if(NOT "${${version}}" MATCHES "^OpenSSL ([0-9]+\\.[0-9]+\\.[0-9]+[a-z]*)( |$)")
      set(${error} "Unrecognized ${version} OpenSSL identity: ${${version}}" PARENT_SCOPE)
      return()
    endif()
    if(NOT CMAKE_MATCH_1 STREQUAL compileVersion)
      set(${error} "${version} version ${CMAKE_MATCH_1} differs from manifest ${compileVersion}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  if(NOT reported_provider STREQUAL provider OR NOT fips STREQUAL "0" OR
     NOT minimum STREQUAL "771" OR NOT peer STREQUAL "1" OR NOT hostname STREQUAL "1")
    return()
  endif()
  set(evidence "{}")
  foreach(key provider requestedLinkage compiled runtime)
    string(REPLACE "\\" "\\\\" escaped "${${key}}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    set(field "${key}")
    if(key STREQUAL "compiled")
      set(field compileVersion)
    elseif(key STREQUAL "runtime")
      set(field runtimeVersion)
    endif()
    string(JSON evidence SET "${evidence}" "${field}" "\"${escaped}\"")
  endforeach()
  string(JSON evidence SET "${evidence}" activeFips false)
  string(JSON evidence SET "${evidence}" minimumTlsVersion "\"1.2\"")
  string(JSON evidence SET "${evidence}" verifyPeer true)
  string(JSON evidence SET "${evidence}" verifyHostname true)
  string(JSON evidence SET "${evidence}" qualificationClaimed false)
  string(JSON evidence SET "${evidence}" policyScope
    "\"Production adapter probe defaults; not driver runtime identity enforcement\"")
  set(${result} "${evidence}" PARENT_SCOPE)
  set(${error} "" PARENT_SCOPE)
endfunction()
