function(odbcpp_json_quote output value)
  string(REPLACE "\\" "\\\\" _value "${value}")
  string(REPLACE "\"" "\\\"" _value "${_value}")
  string(REPLACE "\n" "\\n" _value "${_value}")
  set(${output} "\"${_value}\"" PARENT_SCOPE)
endfunction()

if(DEFINED OpenSSL_VERSION)
  set(ODBCPP_CRYPTO_COMPILE_VERSION "${OpenSSL_VERSION}")
else()
  set(ODBCPP_CRYPTO_COMPILE_VERSION "${OPENSSL_VERSION}")
endif()
if(NOT ODBCPP_CRYPTO_COMPILE_VERSION)
  message(FATAL_ERROR "OpenSSL discovery did not report a compile-time version")
endif()

if(ODBCPP_CRYPTO_LINKAGE STREQUAL "SYSTEM_SHARED")
  set(_dependency_root "null")
  set(_origin "system-discovery")
else()
  odbcpp_json_quote(_dependency_root "${ODBCPP_CRYPTO_ROOT_CANONICAL}")
  set(_origin "controlled-prefix")
endif()
odbcpp_json_quote(_provider "${ODBCPP_CRYPTO_PROVIDER}")
odbcpp_json_quote(_linkage "${ODBCPP_CRYPTO_LINKAGE}")
odbcpp_json_quote(_version "${ODBCPP_CRYPTO_COMPILE_VERSION}")
odbcpp_json_quote(_include "${OPENSSL_INCLUDE_DIR}")
odbcpp_json_quote(_ssl "${OPENSSL_SSL_LIBRARY}")
odbcpp_json_quote(_crypto "${OPENSSL_CRYPTO_LIBRARY}")
odbcpp_json_quote(_origin_json "${_origin}")

set(_manifest "{}")
string(JSON _manifest SET "${_manifest}" schemaVersion 1)
string(JSON _manifest SET "${_manifest}" provider "${_provider}")
string(JSON _manifest SET "${_manifest}" requestedLinkage "${_linkage}")
string(JSON _manifest SET "${_manifest}" compileVersion "${_version}")
string(JSON _manifest SET "${_manifest}" includeDirectory "${_include}")
string(JSON _manifest SET "${_manifest}" sslLinkInput "${_ssl}")
string(JSON _manifest SET "${_manifest}" cryptoLinkInput "${_crypto}")
string(JSON _manifest SET "${_manifest}" dependencyOrigin "${_origin_json}")
string(JSON _manifest SET "${_manifest}" dependencyRoot "${_dependency_root}")
string(JSON _manifest SET "${_manifest}" fipsProfile null)
string(JSON _manifest SET "${_manifest}" fipsClaimed false)
string(JSON _manifest SET "${_manifest}" configurationEvidenceOnly true)
string(JSON _manifest SET "${_manifest}" actualArtifactLinkageVerified false)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/odbcpp-crypto-manifest.json"
     "${_manifest}\n")

message(STATUS "Crypto profile evidence:")
message(STATUS "  Provider: ${ODBCPP_CRYPTO_PROVIDER}")
message(STATUS "  Requested linkage: ${ODBCPP_CRYPTO_LINKAGE}")
message(STATUS "  Compile version: ${ODBCPP_CRYPTO_COMPILE_VERSION}")
message(STATUS "  Origin: ${_origin}")
message(STATUS "  Artifact linkage verified: no")
