if(NOT DEFINED ARTIFACT OR NOT EXISTS "${ARTIFACT}")
  message(FATAL_ERROR "Crypto artifact is missing: ${ARTIFACT}")
endif()
if(NOT EXPECTED_PROVIDER STREQUAL "OPENSSL")
  message(FATAL_ERROR
    "Artifact inspection is not implemented for ${EXPECTED_PROVIDER}")
endif()
if(NOT EXPECTED_LINKAGE MATCHES "^(SYSTEM_SHARED|BUNDLED_SHARED|BUNDLED_STATIC)$")
  message(FATAL_ERROR "Unknown crypto linkage profile: ${EXPECTED_LINKAGE}")
endif()
if(DEFINED INSPECTION_OUTPUT)
  set(_output "${INSPECTION_OUTPUT}")
  set(_tool "test-fixture")
else()
  if(NOT DEFINED INSPECTOR OR NOT EXISTS "${INSPECTOR}")
    message(FATAL_ERROR "Binary dependency inspector is missing: ${INSPECTOR}")
  endif()
  if(PLATFORM STREQUAL "Windows")
    set(_command "${INSPECTOR}" /DEPENDENTS "${ARTIFACT}")
    set(_tool "dumpbin")
  elseif(PLATFORM STREQUAL "Darwin")
    set(_command "${INSPECTOR}" -L "${ARTIFACT}")
    set(_tool "otool")
  elseif(PLATFORM STREQUAL "Linux")
    set(_command "${INSPECTOR}" -d "${ARTIFACT}")
    set(_tool "readelf")
  else()
    message(FATAL_ERROR "Artifact inspection is unsupported on ${PLATFORM}")
  endif()

  execute_process(
    COMMAND ${_command}
    RESULT_VARIABLE _result
    OUTPUT_VARIABLE _output
    ERROR_VARIABLE _error)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR
      "${_tool} failed for ${ARTIFACT}: ${_error}${_output}")
  endif()
endif()
string(TOLOWER "${_output}" _dependencies)

set(_ssl false)
set(_crypto false)
if(_dependencies MATCHES "(lib)?ssl([^a-z0-9_]|$)")
  set(_ssl true)
endif()
if(_dependencies MATCHES "(lib)?crypto([^a-z0-9_]|$)")
  set(_crypto true)
endif()

if(EXPECTED_LINKAGE STREQUAL "BUNDLED_STATIC")
  if(_ssl OR _crypto)
    message(FATAL_ERROR
      "BUNDLED_STATIC artifact has a dynamic OpenSSL dependency:\n${_output}")
  endif()
  set(_observed "static")
else()
  if(NOT _ssl OR NOT _crypto)
    message(FATAL_ERROR
      "Shared crypto profile is missing libssl/libcrypto dependencies:\n${_output}")
  endif()
  set(_observed "shared")
endif()

set(_origin_verified false)
set(_ssl_path "")
set(_crypto_path "")
set(_ssl_input_sha256 "")
set(_crypto_input_sha256 "")
set(_ssl_resolved_sha256 "")
set(_crypto_resolved_sha256 "")
set(_configured_inputs_verified false)

if(DEFINED CONFIG_MANIFEST AND NOT CONFIG_MANIFEST STREQUAL "")
  if(NOT EXISTS "${CONFIG_MANIFEST}")
    message(FATAL_ERROR "Crypto configuration manifest is missing: ${CONFIG_MANIFEST}")
  endif()
  file(READ "${CONFIG_MANIFEST}" _configuration)
  string(JSON _configured_provider ERROR_VARIABLE _config_error
         GET "${_configuration}" provider)
  if(_config_error)
    message(FATAL_ERROR "Crypto configuration manifest is invalid: ${_config_error}")
  endif()
  string(JSON _configured_linkage GET "${_configuration}" requestedLinkage)
  if(NOT _configured_provider STREQUAL EXPECTED_PROVIDER OR
     NOT _configured_linkage STREQUAL EXPECTED_LINKAGE)
    message(FATAL_ERROR "Crypto configuration and artifact profiles differ")
  endif()

  if(EXPECTED_LINKAGE STREQUAL "BUNDLED_STATIC")
    string(JSON _configured_root GET "${_configuration}" dependencyRoot)
    string(JSON _ssl_input GET "${_configuration}" sslLinkInput)
    string(JSON _crypto_input GET "${_configuration}" cryptoLinkInput)
    if(NOT IS_ABSOLUTE "${_configured_root}" OR
       NOT IS_ABSOLUTE "${_ssl_input}" OR
       NOT IS_ABSOLUTE "${_crypto_input}" OR
       NOT EXISTS "${_ssl_input}" OR NOT EXISTS "${_crypto_input}")
      message(FATAL_ERROR
        "Bundled-static origin requires existing absolute link inputs")
    endif()
    file(REAL_PATH "${_configured_root}" _configured_root)
    foreach(_input IN ITEMS "${_ssl_input}" "${_crypto_input}")
      file(REAL_PATH "${_input}" _resolved_input)
      cmake_path(IS_PREFIX _configured_root "${_resolved_input}"
                 NORMALIZE _inside_root)
      if(NOT _inside_root)
        message(FATAL_ERROR
          "Bundled-static link input escaped the controlled dependency root: ${_resolved_input}")
      endif()
    endforeach()
    file(SHA256 "${_ssl_input}" _ssl_input_sha256)
    file(SHA256 "${_crypto_input}" _crypto_input_sha256)
    # The build inputs are controlled and hashed, but a stripped static
    # artifact cannot prove byte-level provenance for embedded provider code.
    set(_configured_inputs_verified true)
  elseif(NOT PLATFORM STREQUAL "Windows")
    if(DEFINED RESOLUTION_OUTPUT)
      set(_resolution "${RESOLUTION_OUTPUT}")
      set(_resolution_tool "test-fixture")
    elseif(PLATFORM STREQUAL "Darwin")
      set(_resolution "${_output}")
      set(_resolution_tool "otool")
    elseif(PLATFORM STREQUAL "Linux")
      if(NOT DEFINED RESOLVER OR NOT EXISTS "${RESOLVER}")
        message(FATAL_ERROR "Runtime dependency resolver is missing: ${RESOLVER}")
      endif()
      execute_process(
        COMMAND "${RESOLVER}" "${ARTIFACT}"
        RESULT_VARIABLE _resolve_result
        OUTPUT_VARIABLE _resolution
        ERROR_VARIABLE _resolve_error)
      if(NOT _resolve_result EQUAL 0)
        message(FATAL_ERROR
          "Runtime dependency resolution failed for ${ARTIFACT}: ${_resolve_error}${_resolution}")
      endif()
      set(_resolution_tool "ldd")
    endif()

    if(PLATFORM STREQUAL "Linux")
      string(REGEX MATCH "(^|\n)[^\n]*libssl[^ \t\n]*[ \t]+=>[ \t]+([^ \t\n]+)"
             _ssl_match "${_resolution}")
      set(_ssl_path "${CMAKE_MATCH_2}")
      string(REGEX MATCH "(^|\n)[^\n]*libcrypto[^ \t\n]*[ \t]+=>[ \t]+([^ \t\n]+)"
             _crypto_match "${_resolution}")
      set(_crypto_path "${CMAKE_MATCH_2}")
    elseif(PLATFORM STREQUAL "Darwin")
      string(REGEX MATCH "(^|\n)[ \t]+([^ \t\n]*libssl[^ \t\n]*)[ \t]+\\("
             _ssl_match "${_resolution}")
      set(_ssl_path "${CMAKE_MATCH_2}")
      string(REGEX MATCH "(^|\n)[ \t]+([^ \t\n]*libcrypto[^ \t\n]*)[ \t]+\\("
             _crypto_match "${_resolution}")
      set(_crypto_path "${CMAKE_MATCH_2}")
    endif()
    if(NOT IS_ABSOLUTE "${_ssl_path}" OR NOT EXISTS "${_ssl_path}" OR
       NOT IS_ABSOLUTE "${_crypto_path}" OR NOT EXISTS "${_crypto_path}")
      message(FATAL_ERROR
        "Shared crypto dependency origin could not be resolved:\n${_resolution}")
    endif()
    file(REAL_PATH "${_ssl_path}" _ssl_path)
    file(REAL_PATH "${_crypto_path}" _crypto_path)
    file(SHA256 "${_ssl_path}" _ssl_resolved_sha256)
    file(SHA256 "${_crypto_path}" _crypto_resolved_sha256)
    if(EXPECTED_LINKAGE STREQUAL "BUNDLED_SHARED")
      string(JSON _configured_root GET "${_configuration}" dependencyRoot)
      file(REAL_PATH "${_configured_root}" _configured_root)
      foreach(_resolved IN ITEMS "${_ssl_path}" "${_crypto_path}")
        cmake_path(IS_PREFIX _configured_root "${_resolved}"
                   NORMALIZE _inside_root)
        if(NOT _inside_root)
          message(FATAL_ERROR
            "Bundled shared dependency escaped the controlled root: ${_resolved}")
        endif()
      endforeach()
    endif()
    set(_origin_verified true)
  endif()
endif()

if(DEFINED EVIDENCE AND NOT EVIDENCE STREQUAL "")
  file(SHA256 "${ARTIFACT}" _sha256)
  get_filename_component(_artifact_name "${ARTIFACT}" NAME)
  set(_evidence "{}")
  string(JSON _evidence SET "${_evidence}" schemaVersion 2)
  string(JSON _evidence SET "${_evidence}" provider "\"${EXPECTED_PROVIDER}\"")
  string(JSON _evidence SET "${_evidence}" requestedLinkage "\"${EXPECTED_LINKAGE}\"")
  string(JSON _evidence SET "${_evidence}" observedDependencyForm "\"${_observed}\"")
  string(JSON _evidence SET "${_evidence}" artifact "\"${_artifact_name}\"")
  string(JSON _evidence SET "${_evidence}" artifactSha256 "\"${_sha256}\"")
  string(JSON _evidence SET "${_evidence}" platform "\"${PLATFORM}\"")
  string(JSON _evidence SET "${_evidence}" inspectionTool "\"${_tool}\"")
  string(JSON _evidence SET "${_evidence}" dependencyFormVerified true)
  string(JSON _evidence SET "${_evidence}" dependencyOriginVerified ${_origin_verified})
  string(JSON _evidence SET "${_evidence}" configuredLinkInputsVerified ${_configured_inputs_verified})
  if(_ssl_path)
    string(JSON _evidence SET "${_evidence}" sslResolvedPath "\"${_ssl_path}\"")
    string(JSON _evidence SET "${_evidence}" cryptoResolvedPath "\"${_crypto_path}\"")
    string(JSON _evidence SET "${_evidence}" resolutionTool "\"${_resolution_tool}\"")
    string(JSON _evidence SET "${_evidence}" sslResolvedSha256 "\"${_ssl_resolved_sha256}\"")
    string(JSON _evidence SET "${_evidence}" cryptoResolvedSha256 "\"${_crypto_resolved_sha256}\"")
  else()
    string(JSON _evidence SET "${_evidence}" sslResolvedPath null)
    string(JSON _evidence SET "${_evidence}" cryptoResolvedPath null)
    string(JSON _evidence SET "${_evidence}" resolutionTool null)
    string(JSON _evidence SET "${_evidence}" sslResolvedSha256 null)
    string(JSON _evidence SET "${_evidence}" cryptoResolvedSha256 null)
  endif()
  if(_ssl_input_sha256)
    string(JSON _evidence SET "${_evidence}" sslLinkInputSha256 "\"${_ssl_input_sha256}\"")
    string(JSON _evidence SET "${_evidence}" cryptoLinkInputSha256 "\"${_crypto_input_sha256}\"")
  else()
    string(JSON _evidence SET "${_evidence}" sslLinkInputSha256 null)
    string(JSON _evidence SET "${_evidence}" cryptoLinkInputSha256 null)
  endif()
  string(JSON _evidence SET "${_evidence}" qualificationClaimed false)
  file(WRITE "${EVIDENCE}" "${_evidence}\n")
endif()
