if(NOT DEFINED ARTIFACT OR NOT EXISTS "${ARTIFACT}")
  message(FATAL_ERROR "Crypto artifact is missing: ${ARTIFACT}")
endif()
if(NOT EXPECTED_PROVIDER STREQUAL "OPENSSL")
  message(FATAL_ERROR
    "Artifact inspection is not implemented for ${EXPECTED_PROVIDER}")
endif()
if(NOT EXPECTED_LINKAGE MATCHES "^(SYSTEM_SHARED|BUNDLED_SHARED|BUNDLED_STATIC)$")
  message(FATAL_ERROR "Unknown crypto linkage profile: ${EXPECTED_LINKAGE}")
endif()
if(DEFINED INSPECTION_OUTPUT)
  set(_output "${INSPECTION_OUTPUT}")
  set(_tool "test-fixture")
else()
  if(NOT DEFINED INSPECTOR OR NOT EXISTS "${INSPECTOR}")
    message(FATAL_ERROR "Binary dependency inspector is missing: ${INSPECTOR}")
  endif()
  if(PLATFORM STREQUAL "Windows")
    set(_command "${INSPECTOR}" /DEPENDENTS "${ARTIFACT}")
    set(_tool "dumpbin")
  elseif(PLATFORM STREQUAL "Darwin")
    set(_command "${INSPECTOR}" -L "${ARTIFACT}")
    set(_tool "otool")
  elseif(PLATFORM STREQUAL "Linux")
    set(_command "${INSPECTOR}" -d "${ARTIFACT}")
    set(_tool "readelf")
  else()
    message(FATAL_ERROR "Artifact inspection is unsupported on ${PLATFORM}")
  endif()

  execute_process(
    COMMAND ${_command}
    RESULT_VARIABLE _result
    OUTPUT_VARIABLE _output
    ERROR_VARIABLE _error)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR
      "${_tool} failed for ${ARTIFACT}: ${_error}${_output}")
  endif()
endif()
string(TOLOWER "${_output}" _dependencies)

set(_ssl false)
set(_crypto false)
if(_dependencies MATCHES "(lib)?ssl([^a-z0-9_]|$)")
  set(_ssl true)
endif()
if(_dependencies MATCHES "(lib)?crypto([^a-z0-9_]|$)")
  set(_crypto true)
endif()

if(EXPECTED_LINKAGE STREQUAL "BUNDLED_STATIC")
  if(_ssl OR _crypto)
    message(FATAL_ERROR
      "BUNDLED_STATIC artifact has a dynamic OpenSSL dependency:\n${_output}")
  endif()
  set(_observed "static")
else()
  if(NOT _ssl OR NOT _crypto)
    message(FATAL_ERROR
      "Shared crypto profile is missing libssl/libcrypto dependencies:\n${_output}")
  endif()
  set(_observed "shared")
endif()

if(DEFINED EVIDENCE AND NOT EVIDENCE STREQUAL "")
  file(SHA256 "${ARTIFACT}" _sha256)
  get_filename_component(_artifact_name "${ARTIFACT}" NAME)
  set(_evidence "{}")
  string(JSON _evidence SET "${_evidence}" schemaVersion 1)
  string(JSON _evidence SET "${_evidence}" provider "\"${EXPECTED_PROVIDER}\"")
  string(JSON _evidence SET "${_evidence}" requestedLinkage "\"${EXPECTED_LINKAGE}\"")
  string(JSON _evidence SET "${_evidence}" observedDependencyForm "\"${_observed}\"")
  string(JSON _evidence SET "${_evidence}" artifact "\"${_artifact_name}\"")
  string(JSON _evidence SET "${_evidence}" artifactSha256 "\"${_sha256}\"")
  string(JSON _evidence SET "${_evidence}" platform "\"${PLATFORM}\"")
  string(JSON _evidence SET "${_evidence}" inspectionTool "\"${_tool}\"")
  string(JSON _evidence SET "${_evidence}" dependencyFormVerified true)
  string(JSON _evidence SET "${_evidence}" dependencyOriginVerified false)
  string(JSON _evidence SET "${_evidence}" qualificationClaimed false)
  file(WRITE "${EVIDENCE}" "${_evidence}\n")
endif()
