# Build-only include ownership. Canonical SDK logical names have one physical owner.
function(odbcpp_resolve_internal_header root logical output)
  if(NOT logical MATCHES "^odbcpp/[A-Za-z0-9_/]+\\.h$")
    if(NOT logical MATCHES "^(core|odbc)/[A-Za-z0-9_/]+\\.h$")
      message(FATAL_ERROR "Invalid internal logical header: ${logical}")
    endif()
    set(${output} "${logical}" PARENT_SCOPE)
    return()
  endif()
  set(_map "${root}/sdk/header_owners.txt")
  if(NOT EXISTS "${_map}")
    message(FATAL_ERROR "Missing canonical SDK header ownership map")
  endif()
  file(STRINGS "${_map}" _owners)
  set(_names "")
  set(_paths "")
  set(_real_paths "")
  set(_selected "")
  foreach(_entry IN LISTS _owners)
    if(NOT _entry MATCHES "^(odbcpp/[A-Za-z0-9_/]+\\.h)\\|(sdk/(include|internal)/odbcpp/[A-Za-z0-9_/]+\\.h)$")
      message(FATAL_ERROR "Invalid canonical SDK owner entry: ${_entry}")
    endif()
    set(_name "${CMAKE_MATCH_1}")
    set(_path "${CMAKE_MATCH_2}")
    string(REGEX REPLACE "^sdk/(include|internal)/" "" _owned_logical "${_path}")
    if(NOT _owned_logical STREQUAL _name)
      message(FATAL_ERROR "Canonical SDK logical/physical owner mismatch: ${_entry}")
    endif()
    if(_name IN_LIST _names OR _path IN_LIST _paths)
      message(FATAL_ERROR "Duplicate or ambiguous canonical SDK owner: ${_entry}")
    endif()
    if(NOT EXISTS "${root}/${_path}")
      message(FATAL_ERROR "Missing canonical SDK owner: ${_path}")
    endif()
    file(REAL_PATH "${root}" _real_root)
    file(REAL_PATH "${root}/${_path}" _real_owner)
    file(RELATIVE_PATH _inside "${_real_root}" "${_real_owner}")
    if(IS_ABSOLUTE "${_inside}" OR _inside MATCHES "^\\.\\./")
      message(FATAL_ERROR "Canonical SDK owner escapes source root: ${_path}")
    endif()
    if(_real_owner IN_LIST _real_paths)
      message(FATAL_ERROR "Aliased canonical SDK physical owner: ${_entry}")
    endif()
    list(APPEND _real_paths "${_real_owner}")
    list(APPEND _names "${_name}")
    list(APPEND _paths "${_path}")
    if(_name STREQUAL logical)
      set(_selected "${_path}")
    endif()
  endforeach()
  if(NOT _selected)
    message(FATAL_ERROR "Unowned canonical SDK header: ${logical}")
  endif()
  set(${output} "${_selected}" PARENT_SCOPE)
endfunction()
function(odbcpp_check_internal_includes root manifest)
  file(REAL_PATH "${root}" _real_root)
  set(_files "")
  file(STRINGS "${manifest}" _headers)
  if(NOT _headers)
    message(FATAL_ERROR "Empty internal header manifest: ${manifest}")
  endif()
  set(_unique ${_headers})
  list(REMOVE_DUPLICATES _unique)
  if(NOT "${_unique}" STREQUAL "${_headers}")
    message(FATAL_ERROR "Duplicate internal header manifest entry: ${manifest}")
  endif()
  foreach(_header IN LISTS _headers)
    odbcpp_resolve_internal_header("${root}" "${_header}" _physical)
    if(NOT EXISTS "${root}/${_physical}")
      message(FATAL_ERROR "Invalid or missing internal header: ${_header}")
    endif()
    file(REAL_PATH "${root}/${_physical}" _real_header)
    file(RELATIVE_PATH _inside "${_real_root}" "${_real_header}")
    if(IS_ABSOLUTE "${_inside}" OR _inside MATCHES "^\\.\\./")
      message(FATAL_ERROR "Internal header symlink escapes source root: ${_header}")
    endif()
    list(APPEND _files "${root}/${_physical}")
  endforeach()
  list(APPEND _files ${ARGN})
  foreach(_file IN LISTS _files)
    file(STRINGS "${_file}" _includes REGEX "^[ \t]*#[ \t]*include")
    foreach(_line IN LISTS _includes)
      if(NOT _line MATCHES "^[ \t]*#[ \t]*include[ \t]*([<\"])([^>\"]+)[>\"]")
        message(FATAL_ERROR "Unverifiable internal include: ${_file}: ${_line}")
      endif()
      set(_delimiter "${CMAKE_MATCH_1}")
      set(_include "${CMAKE_MATCH_2}")
      if(_delimiter STREQUAL "<")
        string(REPLACE "\\" "/" _normalized "${_include}")
        string(TOLOWER "${_normalized}" _normalized)
        if(_normalized MATCHES "(^|/)\\.\\.?(/|$)")
          message(FATAL_ERROR "Angle include contains dot segments: ${_file}: ${_include}")
        endif()
        if(_normalized MATCHES "^(core|odbc|product|odbcpp)/")
          message(FATAL_ERROR "Project header must use a checked quoted include: ${_file}: ${_include}")
        endif()
        continue()
      endif()
      if(_include MATCHES "^(core|odbc|product|odbcpp)/")
        set(_dependency "${_include}")
      else()
        get_filename_component(_parent "${_file}" DIRECTORY)
        get_filename_component(_absolute "${_include}" ABSOLUTE BASE_DIR "${_parent}")
        file(RELATIVE_PATH _dependency "${root}" "${_absolute}")
        # A relative include may resolve to a canonical physical owner.
        set(_logical_matches "")
        foreach(_candidate IN LISTS _headers)
          odbcpp_resolve_internal_header("${root}" "${_candidate}" _candidate_physical)
          if(_candidate_physical STREQUAL _dependency)
            list(APPEND _logical_matches "${_candidate}")
          endif()
        endforeach()
        list(LENGTH _logical_matches _match_count)
        if(_match_count EQUAL 1)
          list(GET _logical_matches 0 _dependency)
        elseif(_match_count GREATER 1)
          message(FATAL_ERROR "Ambiguous relative internal include: ${_file}: ${_include}")
        endif()
      endif()
      if(NOT _dependency IN_LIST _headers)
        message(FATAL_ERROR "Forbidden internal include: ${_file}: ${_include}")
      endif()
    endforeach()
  endforeach()
endfunction()

function(odbcpp_stage_internal_includes part)
  set(_manifest "${CMAKE_CURRENT_SOURCE_DIR}/cmake/internal-headers/${part}.txt")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${_manifest}" "${CMAKE_CURRENT_SOURCE_DIR}/sdk/header_owners.txt" ${ODBCPP_PARTITION_${part}})
  odbcpp_check_internal_includes("${CMAKE_CURRENT_SOURCE_DIR}" "${_manifest}"
    ${ODBCPP_PARTITION_${part}})
  set(_stage "${CMAKE_CURRENT_BINARY_DIR}/internal-include/${part}")
  file(REMOVE_RECURSE "${_stage}")
  file(STRINGS "${_manifest}" _headers)
  foreach(_header IN LISTS _headers)
    odbcpp_resolve_internal_header("${CMAKE_CURRENT_SOURCE_DIR}" "${_header}" _physical)
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/${_physical}" "${_stage}/${_header}" COPYONLY)
  endforeach()
  set(ODBCPP_INTERNAL_INCLUDE_${part} "${_stage}" PARENT_SCOPE)
endfunction()

# Compatibility build surface for wrapper consumers. Production object targets
# continue to use their individual private partition allowlists above.
function(odbcpp_stage_wrapper_includes root destination)
  set(_headers "")
  foreach(_part IN ITEMS runtime backend composition odbc prototype)
    set(_manifest "${root}/cmake/internal-headers/${_part}.txt")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_manifest}")
    odbcpp_check_internal_includes("${root}" "${_manifest}")
    file(STRINGS "${_manifest}" _part_headers)
    list(APPEND _headers ${_part_headers})
  endforeach()
  list(REMOVE_DUPLICATES _headers)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${root}/sdk/header_owners.txt")
  file(REMOVE_RECURSE "${destination}")
  foreach(_header IN LISTS _headers)
    if(_header MATCHES "^odbcpp/auth/")
      message(FATAL_ERROR "Private auth leaked into wrapper include surface")
    endif()
    odbcpp_resolve_internal_header("${root}" "${_header}" _physical)
    configure_file("${root}/${_physical}" "${destination}/${_header}" COPYONLY)
  endforeach()
endfunction()
