# Internal implementation ownership; final artifacts remain flattened archives/DLLs.
function(odbcpp_partition_driver_sources prefix root)
  foreach(_part IN ITEMS runtime backend composition odbc)
    set(_${_part} "")
  endforeach()
  set(_sources ${ARGN})
  list(REMOVE_DUPLICATES _sources)
  foreach(_source IN LISTS _sources)
    if(_source MATCHES "(^|/)connection_pool\\.(cpp|h)$")
      message(FATAL_ERROR "Prototype pool leaked into production partition: ${_source}")
    endif()
    if(_source MATCHES "\\.h$")
      continue()
    endif()
    file(RELATIVE_PATH _relative "${root}" "${_source}")
    if(NOT _relative MATCHES "\\.cpp$")
      message(FATAL_ERROR "Unsupported internal source: ${_relative}")
    elseif(_relative MATCHES "^core/(transport|security|util)/")
      list(APPEND _runtime "${_source}")
    elseif(_relative STREQUAL "core/database/generic_database_connection.cpp" OR
           _relative MATCHES "^core/database/(postgres|mysql|sqlserver)/")
      list(APPEND _backend "${_source}")
    elseif(_relative STREQUAL "product/compiled_backend.cpp" OR
           _relative MATCHES "^core/database/(database_factory|session_owner)\\.cpp$")
      list(APPEND _composition "${_source}")
    elseif(_relative MATCHES "^odbc/")
      list(APPEND _odbc "${_source}")
    else()
      message(FATAL_ERROR "Unclassified internal source: ${_relative}")
    endif()
  endforeach()
  foreach(_part IN ITEMS runtime backend composition odbc)
    if(NOT _${_part})
      message(FATAL_ERROR "Empty internal source partition: ${_part}")
    endif()
    set(${prefix}_${_part} "${_${_part}}" PARENT_SCOPE)
  endforeach()
endfunction()

function(odbcpp_add_internal_objects artifact)
  foreach(_part IN ITEMS runtime backend composition odbc)
    set(_object "${artifact}_${_part}")
    add_library(${_object} OBJECT ${ODBCPP_PARTITION_${_part}})
    target_compile_features(${_object} PRIVATE cxx_std_20)
    set_target_properties(${_object} PROPERTIES POSITION_INDEPENDENT_CODE ON)
    target_include_directories(${_object} PRIVATE "${ODBCPP_INTERNAL_INCLUDE_${_part}}")
    target_include_directories(${_object} SYSTEM PRIVATE "${SPDLOG_INCLUDE_DIR}")
    # Provider usage requirements remain private to compilation; final linkage
    # continues to use the existing artifact's OpenSSL profile and export controls.
    target_link_libraries(${_object} PRIVATE OpenSSL::SSL OpenSSL::Crypto)
    if(_part STREQUAL "composition")
      target_compile_definitions(${_object} PRIVATE ODBCPP_ENABLE_${TARGET_DATABASE}=1)
    endif()
    if(_part STREQUAL "odbc")
      target_include_directories(${_object} PRIVATE "${ODBC_INCLUDE_DIR}")
      if(ODBCPP_EXPECT_DRIVER_SQLWCHAR_SIZE)
        target_compile_definitions(${_object} PRIVATE
          ODBCPP_EXPECT_DRIVER_SQLWCHAR_SIZE=${ODBCPP_EXPECT_DRIVER_SQLWCHAR_SIZE})
      endif()
      if(BUILD_TESTING AND artifact STREQUAL "${PROJECT_NAME}_core")
        target_compile_definitions(${_object} PRIVATE ODBCPP_ENABLE_TEST_HOOKS=1)
      endif()
    endif()
    apply_compiler_settings(${_object})
    # No object-library dependency appears in installed target interfaces.
    target_sources(${artifact} PRIVATE $<TARGET_OBJECTS:${_object}>)
  endforeach()
endfunction()
