# Build-only include ownership. Legacy wrapper/test include interfaces are separate.
function(odbcpp_check_internal_includes root manifest)
  file(REAL_PATH "${root}" _real_root)
  set(_files "")
  file(STRINGS "${manifest}" _headers)
  if(NOT _headers)
    message(FATAL_ERROR "Empty internal header manifest: ${manifest}")
  endif()
  set(_unique ${_headers})
  list(REMOVE_DUPLICATES _unique)
  if(NOT "${_unique}" STREQUAL "${_headers}")
    message(FATAL_ERROR "Duplicate internal header manifest entry: ${manifest}")
  endif()
  foreach(_header IN LISTS _headers)
    if(NOT _header MATCHES "^(core|odbc)/[A-Za-z0-9_/]+\\.h$" OR
       NOT EXISTS "${root}/${_header}")
      message(FATAL_ERROR "Invalid or missing internal header: ${_header}")
    endif()
    file(REAL_PATH "${root}/${_header}" _real_header)
    file(RELATIVE_PATH _inside "${_real_root}" "${_real_header}")
    if(IS_ABSOLUTE "${_inside}" OR _inside MATCHES "^\\.\\./")
      message(FATAL_ERROR "Internal header symlink escapes source root: ${_header}")
    endif()
    list(APPEND _files "${root}/${_header}")
  endforeach()
  list(APPEND _files ${ARGN})
  foreach(_file IN LISTS _files)
    file(STRINGS "${_file}" _includes REGEX "^[ \t]*#[ \t]*include")
    foreach(_line IN LISTS _includes)
      if(NOT _line MATCHES "^[ \t]*#[ \t]*include[ \t]*([<\"])([^>\"]+)[>\"]")
        message(FATAL_ERROR "Unverifiable internal include: ${_file}: ${_line}")
      endif()
      set(_delimiter "${CMAKE_MATCH_1}")
      set(_include "${CMAKE_MATCH_2}")
      if(_delimiter STREQUAL "<")
        string(REPLACE "\\" "/" _normalized "${_include}")
        string(TOLOWER "${_normalized}" _normalized)
        if(_normalized MATCHES "(^|/)\\.\\.?(/|$)")
          message(FATAL_ERROR "Angle include contains dot segments: ${_file}: ${_include}")
        endif()
        if(_normalized MATCHES "^(core|odbc|product)/")
          message(FATAL_ERROR "Project header must use a checked quoted include: ${_file}: ${_include}")
        endif()
        continue()
      endif()
      if(_include MATCHES "^(core|odbc|product)/")
        set(_dependency "${_include}")
      else()
        get_filename_component(_parent "${_file}" DIRECTORY)
        get_filename_component(_absolute "${_include}" ABSOLUTE BASE_DIR "${_parent}")
        file(RELATIVE_PATH _dependency "${root}" "${_absolute}")
      endif()
      if(NOT _dependency IN_LIST _headers)
        message(FATAL_ERROR "Forbidden internal include: ${_file}: ${_include}")
      endif()
    endforeach()
  endforeach()
endfunction()

function(odbcpp_stage_internal_includes part)
  set(_manifest "${CMAKE_CURRENT_SOURCE_DIR}/cmake/internal-headers/${part}.txt")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${_manifest}" ${ODBCPP_PARTITION_${part}})
  odbcpp_check_internal_includes("${CMAKE_CURRENT_SOURCE_DIR}" "${_manifest}"
    ${ODBCPP_PARTITION_${part}})
  set(_stage "${CMAKE_CURRENT_BINARY_DIR}/internal-include/${part}")
  file(REMOVE_RECURSE "${_stage}")
  file(STRINGS "${_manifest}" _headers)
  foreach(_header IN LISTS _headers)
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/${_header}" "${_stage}/${_header}" COPYONLY)
  endforeach()
  set(ODBCPP_INTERNAL_INCLUDE_${part} "${_stage}" PARENT_SCOPE)
endfunction()
