# Configured in the parent build so generator, toolchain and platform match.
function(probe name tree header expected)
  set(_source "${CMAKE_CURRENT_BINARY_DIR}/${name}.cpp")
  set(_checks "")
  if(ARGC GREATER 4)
    set(_checks "${ARGV4}")
  endif()
  file(WRITE "${_source}" "#include <${header}>\n${_checks}\nint main() { return 0; }\n")
  try_compile(_compiled "${CMAKE_CURRENT_BINARY_DIR}/${name}-build" "${_source}"
    CMAKE_FLAGS "-DINCLUDE_DIRECTORIES=${tree}" OUTPUT_VARIABLE _output)
  if(expected)
    if(NOT _compiled)
      message(FATAL_ERROR "Allowed include ${name} failed: ${_output}")
    endif()
  elseif(_compiled OR NOT _output MATCHES "${header}")
    message(FATAL_ERROR "Private include ${name} was not rejected precisely: ${_output}")
  endif()
endfunction()
foreach(_part IN ITEMS runtime backend composition odbc)
  if(NOT IS_DIRECTORY "${INCLUDE_ROOT}/${_part}")
    message(FATAL_ERROR "Missing internal include tree: ${_part}")
  endif()
endforeach()
probe(runtime_transport "${INCLUDE_ROOT}/runtime" odbcpp/transport/i_transport.h TRUE)
probe(odbc_contract "${INCLUDE_ROOT}/odbc" odbcpp/database/backend_provider.h TRUE)
probe(backend_provider "${INCLUDE_ROOT}/backend" core/database/postgres/pg_backend_provider.h TRUE)
probe(composition_provider "${INCLUDE_ROOT}/composition" core/database/postgres/pg_backend_provider.h TRUE)
probe(runtime_session "${INCLUDE_ROOT}/runtime" odbcpp/database/i_database_connection.h FALSE)
probe(odbc_parser "${INCLUDE_ROOT}/odbc" core/database/postgres/pg_protocol_parser.h FALSE)
probe(odbc_pool "${INCLUDE_ROOT}/odbc" core/database/connection_pool.h FALSE)
probe(backend_odbc "${INCLUDE_ROOT}/backend" odbc/odbc_types.h FALSE)
probe(composition_parser "${INCLUDE_ROOT}/composition" core/database/i_protocol_parser.h FALSE)
probe(composition_pool "${INCLUDE_ROOT}/composition" core/database/connection_pool.h FALSE)

probe(composition_session_owner "${INCLUDE_ROOT}/composition" odbcpp/session/session_owner.h TRUE)
probe(backend_session_owner "${INCLUDE_ROOT}/backend" odbcpp/session/session_owner.h FALSE)
probe(odbc_session_owner "${INCLUDE_ROOT}/odbc" odbcpp/session/session_owner.h TRUE
  "#include <type_traits>\ntemplate<class T> concept Complete = requires { sizeof(T); };\nstatic_assert(!Complete<rs::core::database::CredentialContext>);\nstatic_assert(!Complete<rs::core::database::CredentialToken>);\nstatic_assert(std::is_move_constructible_v<rs::core::database::SessionOwner>);\nstatic_assert(std::is_move_constructible_v<rs::core::database::SessionLease>);\nstatic_assert(std::is_constructible_v<rs::core::database::SessionOwner, std::unique_ptr<rs::core::database::IDatabaseConnection>>);")

probe(composition_credentials "${INCLUDE_ROOT}/composition" odbcpp/session/credential_context.h TRUE)
probe(backend_credentials "${INCLUDE_ROOT}/backend" odbcpp/session/credential_context.h FALSE)
probe(odbc_credentials "${INCLUDE_ROOT}/odbc" odbcpp/session/credential_context.h FALSE)
