include("${CMAKE_CURRENT_LIST_DIR}/CryptoIdentityEvidence.cmake")
if(NOT DEFINED EVIDENCE OR EVIDENCE STREQUAL "")
  message(FATAL_ERROR "Identity evidence output path is required")
endif()
# Remove previous evidence first so failure cannot leave a stale success record.
file(REMOVE "${EVIDENCE}")
foreach(input PROBE MANIFEST ARTIFACT)
  if(NOT DEFINED ${input} OR NOT EXISTS "${${input}}")
    message(FATAL_ERROR "Identity input ${input} is missing")
  endif()
endforeach()
execute_process(COMMAND "${PROBE}" RESULT_VARIABLE status
  OUTPUT_VARIABLE output ERROR_VARIABLE stderr TIMEOUT 15)
if(NOT status STREQUAL "0")
  message(FATAL_ERROR "Production identity probe failed: ${status}: ${stderr}")
endif()
file(READ "${MANIFEST}" manifest)
validate_crypto_identity("${output}" "${manifest}" evidence error)
if(error)
  message(FATAL_ERROR "${error}\nNon-secret production probe identity:\n${output}")
endif()
foreach(input PROBE MANIFEST ARTIFACT)
  file(SHA256 "${${input}}" digest)
  string(TOLOWER "${input}" field)
  string(JSON evidence SET "${evidence}" "${field}Sha256" "\"${digest}\"")
endforeach()
file(WRITE "${EVIDENCE}" "${evidence}\n")
