set(root "${BINARY_DIR}/crypto-identity-recording-fixture")
file(MAKE_DIRECTORY "${root}")
set(evidence "${root}/evidence.json")
set(recorder "${CMAKE_CURRENT_LIST_DIR}/RecordCryptoIdentity.cmake")
function(record probe manifest expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPROBE=${probe}"
    "-DMANIFEST=${manifest}" "-DARTIFACT=${ARTIFACT}" "-DEVIDENCE=${evidence}"
    -P "${recorder}" RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(expected)
    if(NOT status STREQUAL "0" OR NOT EXISTS "${evidence}")
      message(FATAL_ERROR "Identity recording failed: ${stdout}${stderr}")
    endif()
  elseif(status STREQUAL "0" OR EXISTS "${evidence}")
    message(FATAL_ERROR "Failed identity recording retained success evidence")
  endif()
endfunction()
record("${PROBE}" "${MANIFEST}" TRUE)
file(READ "${evidence}" result)
foreach(input PROBE MANIFEST ARTIFACT)
  string(TOLOWER "${input}" field)
  string(JSON actual GET "${result}" "${field}Sha256")
  file(SHA256 "${${input}}" expected)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Identity evidence is not bound to ${input}")
  endif()
endforeach()
file(READ "${MANIFEST}" manifest)
string(JSON manifest SET "${manifest}" compileVersion "\"0.0.0\"")
file(WRITE "${root}/wrong-manifest.json" "${manifest}")
record("${PROBE}" "${root}/wrong-manifest.json" FALSE)
file(WRITE "${evidence}" "stale success")
record("${root}/missing-probe" "${MANIFEST}" FALSE)
record("${PROBE}" "${MANIFEST}" TRUE)
