cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED CHECKER OR NOT DEFINED FIXTURE_DIR)
  message(FATAL_ERROR "CHECKER and FIXTURE_DIR are required")
endif()
file(REMOVE_RECURSE "${FIXTURE_DIR}")
file(MAKE_DIRECTORY "${FIXTURE_DIR}/core/database")
set(_manifest "${FIXTURE_DIR}/manifest.txt")
function(check_fixture name contents manifest expected)
  file(WRITE "${FIXTURE_DIR}/core/database/probe.h" "${contents}")
  file(WRITE "${_manifest}" "${manifest}")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE_DIR=${FIXTURE_DIR}"
    "-DMANIFEST=${_manifest}" -P "${CHECKER}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
  if(expected STREQUAL "PASS")
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Valid fixture ${name} rejected: ${_output}${_error}")
    endif()
  elseif(_result EQUAL 0 OR NOT "${_output}${_error}" MATCHES "${expected}")
    message(FATAL_ERROR "Invalid fixture ${name} was not rejected precisely: ${_output}${_error}")
  endif()
endfunction()
set(_one "core/database/probe.h\n")
check_fixture(diagnostic "const char* text = \"TLS/SSL error\";\n" "${_one}" PASS)
check_fixture(standard "#include <string>\n#include <span>\n" "${_one}" PASS)
file(WRITE "${FIXTURE_DIR}/core/database/leaf.h" "#pragma once\n")
check_fixture(local "#include \"leaf.h\"\n#include \"core/database/leaf.h\"\n"
  "${_one}core/database/leaf.h\n" PASS)
check_fixture(odbc "#include <sql.h>\n" "${_one}" "Non-standard dependency")
check_fixture(crypto "#include <openssl/ssl.h>\n" "${_one}" "Non-standard dependency")
check_fixture(backend "#include \"postgres/pg_protocol_parser.h\"\n" "${_one}" "Unlisted dependency")
check_fixture(unlisted "#include \"leaf.h\"\n" "${_one}" "Unlisted dependency")
check_fixture(escape "#include \"../../../outside.h\"\n" "${_one}" "Unlisted dependency")
check_fixture(macro "#include SDK_EXTERNAL_HEADER\n" "${_one}" "Unverifiable SDK contract include")
check_fixture(selection "#ifdef ODBCPP_ENABLE_POSTGRESQL\n#endif\n" "${_one}" "selection leaked")
check_fixture(type "struct SSL_CTX;\n" "${_one}" "type or selection leaked")
check_fixture(evp_type "struct EVP_MD_CTX;\n" "${_one}" "type or selection leaked")
check_fixture(odbc_type "using Token = SQLHANDLE;\n" "${_one}" "type or selection leaked")
check_fixture(duplicate "#pragma once\n" "${_one}${_one}" "duplicate entries")
check_fixture(missing "#pragma once\n" "core/database/missing.h\n" "Missing SDK contract header")
check_fixture(private "#pragma once\n" "core/database/parsed_query_result.h\n" "Private implementation")
check_fixture(private_owner "#pragma once\n" "core/database/session_owner.h\n" "Private implementation")
check_fixture(invalid_entry "#pragma once\n" "../outside.h\n" "Invalid SDK contract manifest entry")
check_fixture(empty "#pragma once\n" "" "manifest is empty")
