cmake_minimum_required(VERSION 3.20)
include("${SOURCE_DIR}/cmake/DriverSources.cmake")
foreach(_database IN ITEMS POSTGRESQL REDSHIFT)
  odbcpp_collect_driver_sources(_sources "${_database}")
  odbcpp_check_prototype_quarantine(${_sources})
endforeach()
set(_fixture "${BINARY_DIR}/prototype-quarantine")
file(MAKE_DIRECTORY "${_fixture}")
file(WRITE "${_fixture}/bad.cmake" "cmake_minimum_required(VERSION 3.20)\ninclude(\"${SOURCE_DIR}/cmake/PrototypePool.cmake\")\nodbcpp_check_prototype_quarantine(\"${SOURCE_DIR}/core/database/connection_pool.cpp\")\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -P "${_fixture}/bad.cmake"
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "Prototype pool leaked")
  message(FATAL_ERROR "Prototype inventory leakage was not rejected precisely: ${_out}${_err}")
endif()
# Target guard catches accidental direct/interface dependencies and raw sources.
foreach(_kind IN ITEMS link source object)
  set(_target_fixture "${_fixture}/target-${_kind}")
  file(MAKE_DIRECTORY "${_target_fixture}")
  set(_declaration "add_library(bad INTERFACE)")
  if(_kind STREQUAL "link")
    set(_leak "target_link_libraries(bad INTERFACE odbcpp_prototype_pool)")
  elseif(_kind STREQUAL "object")
    file(WRITE "${_target_fixture}/connection_pool.cpp" "// negative fixture\n")
    set(_declaration "add_library(bad OBJECT connection_pool.cpp)")
    set(_leak "")
  else()
    set(_leak "target_sources(bad INTERFACE connection_pool.cpp)")
  endif()
  file(WRITE "${_target_fixture}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.20)\nproject(QuarantineGuard NONE)\ninclude(\"${SOURCE_DIR}/cmake/PrototypePool.cmake\")\nadd_library(quarantine_clean INTERFACE)\nodbcpp_check_prototype_target(quarantine_clean)\n${_declaration}\n${_leak}\nodbcpp_check_prototype_target(bad)\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_target_fixture}" -B "${_target_fixture}/build"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "Prototype pool leaked into production target")
    message(FATAL_ERROR "Prototype target ${_kind} leakage was not rejected precisely: ${_out}${_err}")
  endif()
endforeach()
set(_prefix "${_fixture}/installed headers")
file(REMOVE_RECURSE "${_prefix}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BINARY_DIR}"
  --prefix "${_prefix}" --config "${CONFIG}"
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(NOT _result EQUAL 0)
  message(FATAL_ERROR "Private-prefix installation failed: ${_out}${_err}")
endif()
if(NOT EXISTS "${_prefix}/include/odbcpp/core/database/i_database_connection.h")
  message(FATAL_ERROR "Control installed session header is missing")
endif()
file(GLOB_RECURSE _installed "${_prefix}/*")
foreach(_file IN LISTS _installed)
  if(_file MATCHES "/(connection_pool|session_owner)\\.h$|/connection_pool_example\\.cpp$")
    message(FATAL_ERROR "Private ownership or prototype surface leaked into installed development surface: ${_file}")
  endif()
endforeach()
