cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED SOURCE_DIR OR NOT DEFINED FIXTURE_DIR)
  message(FATAL_ERROR "SOURCE_DIR and FIXTURE_DIR are required")
endif()
file(MAKE_DIRECTORY "${FIXTURE_DIR}/core/database" "${FIXTURE_DIR}/odbc")
set(_manifest "${FIXTURE_DIR}/headers.txt")
set(_source "${FIXTURE_DIR}/odbc/probe.cpp")
file(WRITE "${FIXTURE_DIR}/core/database/leaf.h" "#pragma once\n")
file(WRITE "${FIXTURE_DIR}/core/database/contract.h" "#include \"leaf.h\"\n")
function(check_fixture name contents headers expected)
  file(WRITE "${_source}" "${contents}")
  file(WRITE "${_manifest}" "${headers}")
  set(_script "${FIXTURE_DIR}/${name}.cmake")
  file(WRITE "${_script}" "cmake_minimum_required(VERSION 3.20)\ninclude(\"${SOURCE_DIR}/cmake/InternalIncludes.cmake\")\nodbcpp_check_internal_includes(\"${FIXTURE_DIR}\" \"${_manifest}\" \"${_source}\")\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" -P "${_script}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(expected STREQUAL "PASS")
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Allowed ${name} include failed: ${_out}${_err}")
    endif()
  elseif(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${expected}")
    message(FATAL_ERROR "Invalid ${name} include was not rejected precisely: ${_out}${_err}")
  endif()
endfunction()
set(_headers "core/database/contract.h\ncore/database/leaf.h\n")
check_fixture(root "#include \"core/database/contract.h\"\n" "${_headers}" PASS)
check_fixture(relative "#include \"../core/database/contract.h\"\n" "${_headers}" PASS)
check_fixture(transitive "#include \"core/database/contract.h\"\n" "core/database/contract.h\n" "Forbidden internal include")
check_fixture(private "#include \"core/database/i_protocol_parser.h\"\n" "${_headers}" "Forbidden internal include")
check_fixture(escape "#include \"../../outside.h\"\n" "${_headers}" "Forbidden internal include")
check_fixture(macro "#include INTERNAL_HEADER\n" "${_headers}" "Unverifiable internal include")
check_fixture(angle "#include <core/database/leaf.h>\n" "${_headers}" "Project header must")
check_fixture(duplicate "" "${_headers}${_headers}" "Duplicate internal header")
check_fixture(missing "" "core/database/missing.h\n" "Invalid or missing internal header")
check_fixture(empty "" "" "Empty internal header manifest")

check_fixture(angle_dot "#include <./core/database/leaf.h>\n" "${_headers}" "Angle include contains dot segments")
check_fixture(angle_parent "#include <../backend/core/database/leaf.h>\n" "${_headers}" "Angle include contains dot segments")
check_fixture(angle_case "#include <Core/database/leaf.h>\n" "${_headers}" "Project header must")
check_fixture(angle_backslash "#include <core\\database\\leaf.h>\n" "${_headers}" "Project header must")
file(WRITE "${FIXTURE_DIR}/outside.h" "#pragma once\n")
file(MAKE_DIRECTORY "${FIXTURE_DIR}/narrow/core/database")
file(REMOVE "${FIXTURE_DIR}/narrow/core/database/escape.h")
file(CREATE_LINK "${FIXTURE_DIR}/outside.h" "${FIXTURE_DIR}/narrow/core/database/escape.h" SYMBOLIC RESULT _link_result)
if(_link_result STREQUAL "0")
  file(WRITE "${_manifest}" "core/database/escape.h\n")
  file(WRITE "${FIXTURE_DIR}/symlink.cmake" "cmake_minimum_required(VERSION 3.20)\ninclude(\"${SOURCE_DIR}/cmake/InternalIncludes.cmake\")\nodbcpp_check_internal_includes(\"${FIXTURE_DIR}/narrow\" \"${_manifest}\")\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" -P "${FIXTURE_DIR}/symlink.cmake"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "symlink escapes source root")
    message(FATAL_ERROR "Symlink escape was not rejected precisely: ${_out}${_err}")
  endif()
else()
  message(STATUS "Symlink fixture unavailable on this host: ${_link_result}")
endif()

# An incremental build must recheck original source-directory quoted includes.
set(_incremental "${FIXTURE_DIR}/incremental")
file(MAKE_DIRECTORY "${_incremental}/cmake/internal-headers" "${_incremental}/core/database")
file(WRITE "${_incremental}/cmake/internal-headers/composition.txt" "core/database/allowed.h\n")
file(WRITE "${_incremental}/core/database/allowed.h" "#pragma once\n")
file(WRITE "${_incremental}/core/database/private.h" "#pragma once\n")
file(WRITE "${_incremental}/core/database/source.cpp" "#include \"allowed.h\"\n")
file(WRITE "${_incremental}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.20)\nproject(IncrementalClosure NONE)\ninclude(\"${SOURCE_DIR}/cmake/InternalIncludes.cmake\")\nset(ODBCPP_PARTITION_composition \"${_incremental}/core/database/source.cpp\")\nodbcpp_stage_internal_includes(composition)\nadd_custom_target(check ALL)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_incremental}" -B "${_incremental}/build"
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(NOT _result EQUAL 0)
  message(FATAL_ERROR "Incremental fixture configure failed: ${_out}${_err}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_incremental}/build"
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(NOT _result EQUAL 0)
  message(FATAL_ERROR "Allowed incremental fixture failed: ${_out}${_err}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1)
file(APPEND "${_incremental}/core/database/source.cpp" "#include \"private.h\"\n")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_incremental}/build"
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "Forbidden internal include")
  message(FATAL_ERROR "Incremental source edit bypassed closure check: ${_out}${_err}")
endif()

# Canonical SDK headers resolve through one explicit physical owner.
file(MAKE_DIRECTORY "${FIXTURE_DIR}/sdk/include/odbcpp/database")
file(WRITE "${FIXTURE_DIR}/sdk/include/odbcpp/database/leaf.h" "#pragma once\n")
set(_owner "odbcpp/database/leaf.h|sdk/include/odbcpp/database/leaf.h\n")
file(WRITE "${FIXTURE_DIR}/sdk/header_owners.txt" "${_owner}")
check_fixture(canonical "#include \"odbcpp/database/leaf.h\"\n" "odbcpp/database/leaf.h\n" PASS)
check_fixture(canonical_relative "#include \"../sdk/include/odbcpp/database/leaf.h\"\n" "odbcpp/database/leaf.h\n" PASS)
check_fixture(canonical_angle "#include <odbcpp/database/leaf.h>\n" "odbcpp/database/leaf.h\n" "Project header must")
check_fixture(canonical_unowned "" "odbcpp/database/unowned.h\n" "Unowned canonical SDK header")
file(WRITE "${FIXTURE_DIR}/sdk/header_owners.txt" "${_owner}${_owner}")
check_fixture(canonical_duplicate "" "odbcpp/database/leaf.h\n" "Duplicate or ambiguous canonical SDK owner")
file(WRITE "${FIXTURE_DIR}/sdk/header_owners.txt" "odbcpp/database/other.h|sdk/include/odbcpp/database/leaf.h\n")
check_fixture(canonical_mismatch "" "odbcpp/database/other.h\n" "logical/physical owner mismatch")
file(WRITE "${FIXTURE_DIR}/sdk/header_owners.txt" "odbcpp/database/leaf.h|../escape.h\n")
check_fixture(canonical_escape "" "odbcpp/database/leaf.h\n" "Invalid canonical SDK owner entry")
file(WRITE "${FIXTURE_DIR}/sdk/header_owners.txt" "${_owner}")
