include("${CMAKE_CURRENT_LIST_DIR}/CryptoIdentityEvidence.cmake")
set(manifest "{\"provider\":\"OPENSSL\",\"compileVersion\":\"3.0.16\",\"requestedLinkage\":\"SYSTEM_SHARED\"}")
set(good "OPENSSL\nOpenSSL 3.0.16 11 Feb 2025\nOpenSSL 3.0.16 11 Feb 2025\n0\n771\n1\n1\n")
function(check name raw config expected)
  validate_crypto_identity("${raw}" "${config}" evidence error)
  if(expected)
    if(error OR NOT evidence)
      message(FATAL_ERROR "${name}: valid identity rejected: ${error}")
    endif()
    string(JSON claimed GET "${evidence}" qualificationClaimed)
    if(claimed)
      message(FATAL_ERROR "${name}: unsupported qualification claim")
    endif()
    string(REPLACE "\r\n" "\n" normalized "${raw}")
    string(REPLACE "\n" ";" fields "${normalized}")
    list(GET fields 1 expected_compile)
    list(GET fields 2 expected_runtime)
    string(JSON actual_compile GET "${evidence}" compileVersion)
    string(JSON actual_runtime GET "${evidence}" runtimeVersion)
    if(NOT actual_compile STREQUAL expected_compile OR NOT actual_runtime STREQUAL expected_runtime)
      message(FATAL_ERROR "${name}: serialized identity version fields differ")
    endif()
  elseif(NOT error OR evidence)
    message(FATAL_ERROR "${name}: invalid identity accepted")
  endif()
endfunction()
check(valid "${good}" "${manifest}" TRUE)
string(REPLACE "\n" "\r\n" windows "${good}")
check(windows_newlines "${windows}" "${manifest}" TRUE)
string(REPLACE "3.0.16" "1.1.1w" legacy "${good}")
string(REPLACE "3.0.16" "1.1.1w" legacy_manifest "${manifest}")
check(legacy_version "${legacy}" "${legacy_manifest}" TRUE)
foreach(linkage BUNDLED_SHARED BUNDLED_STATIC)
  string(REPLACE "SYSTEM_SHARED" "${linkage}" config "${manifest}")
  check("${linkage}" "${good}" "${config}" TRUE)
endforeach()
foreach(pair "0\n771|1\n771" "771|770" "1\n1\n|0\n1\n" "1\n1\n|1\n0\n"
             "OPENSSL|AWS_LC" "OpenSSL 3.0.16 11 Feb 2025\n0|OpenSSL 3.0.17 11 Feb 2025\n0"
             "OpenSSL 3.0.16|OpenSSL incompatible")
  string(REPLACE "|" ";" parts "${pair}")
  list(GET parts 0 before)
  list(GET parts 1 after)
  string(REPLACE "${before}" "${after}" bad "${good}")
  check("negative ${before}" "${bad}" "${manifest}" FALSE)
endforeach()
string(REPLACE "OPENSSL" "OPENSSL;extra" delimiter "${good}")
check(delimiter_injection "${delimiter}" "${manifest}" FALSE)
check(truncated "OPENSSL\nOpenSSL 3.0.16" "${manifest}" FALSE)
check(extra "${good}extra\n" "${manifest}" FALSE)
check(empty "" "${manifest}" FALSE)
check(malformed_json "${good}" "{}" FALSE)
string(REPLACE "3.0.16" "3.0.15" wrong_version "${manifest}")
check(manifest_mismatch "${good}" "${wrong_version}" FALSE)
string(REPLACE "3.0.16" "3.0.160" prefix "${good}")
check(version_prefix "${prefix}" "${manifest}" FALSE)
set(windows_mismatch "OPENSSL\nOpenSSL 3.6.4 25 Aug 2026\nOpenSSL 3.5.5 27 Jan 2026\n0\n771\n1\n1\n")
string(REPLACE "3.0.16" "3.6.4" windows_manifest "${manifest}")
check(windows_wrong_runtime "${windows_mismatch}" "${windows_manifest}" FALSE)
check(invalid_json "${good}" "{invalid" FALSE)
